#!/bin/bash

set -eu

cd "$(dirname $0)"

rm -rf tpch-dbgen
git clone https://github.com/electrum/tpch-dbgen
cd tpch-dbgen
make -j$(nproc)

# Create ~0.01GB files
./dbgen -vf -s 0.01
mkdir -p $OPAQUE_DATA_DIR/tpch/sf_001
chmod u+r *.tbl
cp *.tbl $OPAQUE_DATA_DIR/tpch/sf_001
