#!/bin/bash

set -eu

cd "$(dirname $0)"

rm -rf tpch-dbgen
git clone https://github.com/electrum/tpch-dbgen
cd tpch-dbgen
make
./dbgen -vf -s 0.01
mkdir -p $SPARKSGX_DATA_DIR/tpch/sf_small
ls -la # For debugging "permission denied" errors on the next line
cp *.tbl $SPARKSGX_DATA_DIR/tpch/sf_small/
