/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_sql_SGXEnclave */

#ifndef _Included_org_apache_spark_sql_SGXEnclave
#define _Included_org_apache_spark_sql_SGXEnclave
#ifdef __cplusplus
extern "C" {
#endif
  /*
   * Class:     org_apache_spark_sql_SGXEnclave
   * Method:    StartEnclave
   * Signature: ()J
   */
  JNIEXPORT jlong JNICALL Java_org_apache_spark_sql_SGXEnclave_StartEnclave
  (JNIEnv *, jobject);

  /*
   * Class:     org_apache_spark_sql_SGXEnclave
   * Method:    StopEnclave
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL Java_org_apache_spark_sql_SGXEnclave_StopEnclave
  (JNIEnv *, jobject, jlong);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_Project(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_Filter(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jobject);

  /*
   * Class:     org_apache_spark_sql_SGXEnclave
   * Method:    Encrypt
   * Signature: (J[B)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_Encrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

  /*
   * Class:     org_apache_spark_sql_SGXEnclave
   * Method:    Decrypt
   * Signature: (J[B)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_Decrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

  /*
   * Class:     org_apache_spark_sql_SGXEnclave
   * Method:    Test
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL Java_org_apache_spark_sql_SGXEnclave_Test
  (JNIEnv *, jobject, jlong);

  /*
   * Class:     org_apache_spark_sql_SGXEnclave
   * Method:    ObliviousSort
   * Signature: (JI[BII)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_ObliviousSort
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_AggregateStep1(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_ProcessBoundary(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_AggregateStep2(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jbyteArray);


  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_JoinSortPreprocess(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jbyteArray, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_ScanCollectLastPrimary(JNIEnv *,
                                                                                           jobject,
                                                                                           jlong,
                                                                                           jint,
                                                                                           jbyteArray,
                                                                                           jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_ProcessJoinBoundary(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_SortMergeJoin(JNIEnv *,
                                                                                  jobject,
                                                                                  jlong,
                                                                                  jint,
                                                                                  jbyteArray,
                                                                                  jint,
                                                                                  jbyteArray);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_EncryptAttribute(JNIEnv *,
                                                                                     jobject,
                                                                                     jlong,
                                                                                     jbyteArray);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_CreateBlock(
    JNIEnv *, jobject, jlong, jbyteArray, jint, jboolean);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_SplitBlock(
    JNIEnv *, jobject, jlong, jbyteArray, jint, jboolean);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_PartitionForSort(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jint, jintArray, jintArray);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_ExternalSort(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_NonObliviousAggregate(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jobject);

  JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sql_SGXEnclave_NonObliviousSortMergeJoin(
    JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jobject);
  
#ifdef __cplusplus
}
#endif
#endif
