/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class map_test_SGX */

#ifndef _Included_map_test_SGX
#define _Included_map_test_SGX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     map_test_SGX
 * Method:    StartEnclave
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_map_1test_SGX_StartEnclave
  (JNIEnv *, jobject);

/*
 * Class:     map_test_SGX
 * Method:    StopEnclave
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_map_1test_SGX_StopEnclave
  (JNIEnv *, jobject, jlong);

/*
 * Class:     map_test_SGX
 * Method:    IncByOne
 * Signature: (J[I)[I
 */
JNIEXPORT jintArray JNICALL Java_map_1test_SGX_IncByOne
  (JNIEnv *, jobject, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
