# Set up docker container for simulate mode

FROM ubuntu:18.04

# Download all dependencies. Step 1 of Opaque and step 3 of open-enclave

RUN apt-get update && \
	apt-get install -y sudo wget build-essential openjdk-8-jdk python libssl-dev

RUN wget https://github.com/Kitware/CMake/releases/download/v3.15.6/cmake-3.15.6-Linux-x86_64.sh
RUN sudo bash cmake-3.15.6-Linux-x86_64.sh --skip-license --prefix=/usr/local

# Step 1 of open-enclave

RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
RUN wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -

RUN echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-bionic-7.list
RUN wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

RUN echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main" | sudo tee /etc/apt/sources.list.d/msprod.list
RUN wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Step 3 of open-enclave

RUN apt-get update && \
	apt-get install -y clang-7 libssl-dev gdb libsgx-enclave-common libsgx-enclave-common-dev libprotobuf10 libsgx-dcap-ql libsgx-dcap-ql-dev az-dcap-client open-enclave=0.9.0 curl git

# Occasionally, the sbt command will fail because of failure to download. Pre-download sbt-launch jar for build/sbt

WORKDIR /root/.sbt/launchers/0.13.17

RUN curl -L -o /root/.sbt/launchers/0.13.17/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.17/sbt-launch.jar

# Get the Opaque repository
WORKDIR /root
RUN git clone https://github.com/ucbrise/opaque.git

WORKDIR /root/opaque

# Create private key. Step 2 of Opaque
RUN openssl genrsa -out private_key.pem -3 3072

# Set env variables
ENV MODE=SIMULATE
ENV OPAQUE_HOME=/root/opaque
ENV SPARKSGX_DATA_DIR=/root/opaque/data/
ENV PRIVATE_KEY_PATH=/root/opaque/private_key.pem
ENV OE_SDK_PATH=/opt/openenclave/

ENV PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/opt/openenclave/share/pkgconfig
ENV CMAKE_PREFIX_PATH=/opt/openenclave/lib/openenclave/cmake
ENV PATH=${PATH}:/opt/openenclave/bin

RUN build/sbt test
