#!/bin/bash

remote="$1"
url="$2"

# Run scalafmt and check format
echo "* Checking changed Scala files for formatting..."
(cd ${OPAQUE_HOME}/; scalafmt --diff)
git diff --quiet
echo "* Done!"
echo "* The following files needed formatting:"
git diff --name-only
git add -u

# Run git-clang-format and check format
echo "* Checking changed C/C++ files for formatting..."
(cd ${OPAQUE_HOME}/; git-clang-format HEAD~1)
git diff --quiet
echo "* Done!"
echo "* The following files needed formatting:"
git diff --name-only
git add -u

echo "* Pre-push hook finished."

exit 0

