#!/bin/bash

remote="$1"
url="$2"

# Run scalafmt and check format
echo "* Checking changed scala files for formatting..."
(cd ${OPAQUE_HOME}/; scalafmt --diff)
git diff --quiet
formatted=$?
echo "* Done!"
echo "* Scala properly formatted?"
if [ $formatted -eq 0 ]
then
   echo "* Yes"
else
    echo "* No"
    echo "The following files need formatting:"
    git diff --name-only
    echo "Running 'scalafmt' to format the code."
    scalafmt --diff
    exit 1
fi

exit 0

