#!/bin/bash

remote="$1"
url="$2"

# Run scalafmt and check format
echo "* Checking changed scala files for formatting..."
(cd ${OPAQUE_HOME}/; scalafmt --diff)
git diff --quiet
echo "* Done!"
echo "* The following files needed formatting:"
git diff --name-only
git add -u

exit 0

